/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import helper.DataHolder;
import helper.WindowStack;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import objetos.DadosGerais;

/**
 *
 * @author macha
 */
public class JanelaDadosGerais extends javax.swing.JFrame {

    /**
     * Creates new form JanelaDadosGerais
     */
    public JanelaDadosGerais() {
        initComponents();
        
        if (DataHolder.getInstance().dadosGerais == null) {
            DataHolder.getInstance().dadosGerais = new DadosGerais(
                    this.obra.getText(),
                    this.scan.getText(),
                    this.tradutor.getText(),
                    this.capitulo.getText(),
                    1
            );
        }
        DadosGerais dadosGerais = DataHolder.getInstance().dadosGerais;
        this.obra.setText(dadosGerais.obra);
        this.scan.setText(dadosGerais.scan);
        this.tradutor.setText(dadosGerais.tradutor);
        this.capitulo.setText(dadosGerais.capitulo);
        this.paginas.setText(dadosGerais.ultimaPagina.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        obrap = new javax.swing.JPanel();
        obra = new javax.swing.JTextField();
        scanp = new javax.swing.JPanel();
        scan = new javax.swing.JTextField();
        tradutorp = new javax.swing.JPanel();
        tradutor = new javax.swing.JTextField();
        capitulop = new javax.swing.JPanel();
        capitulo = new javax.swing.JTextField();
        paginasp = new javax.swing.JPanel();
        paginas = new javax.swing.JTextField();
        botoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados Gerais");
        setMaximumSize(new java.awt.Dimension(500, 175));
        setPreferredSize(new java.awt.Dimension(500, 300));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        obrap.setBorder(javax.swing.BorderFactory.createTitledBorder("TITULO:"));
        obrap.setMaximumSize(new java.awt.Dimension(500, 500));
        obrap.setMinimumSize(new java.awt.Dimension(500, 25));
        obrap.setLayout(new java.awt.BorderLayout());

        obra.setMaximumSize(new java.awt.Dimension(300, 25));
        obra.setMinimumSize(new java.awt.Dimension(300, 25));
        obra.setPreferredSize(new java.awt.Dimension(300, 25));
        obrap.add(obra, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(obrap);

        scanp.setBorder(javax.swing.BorderFactory.createTitledBorder("SCAN:"));
        scanp.setMaximumSize(new java.awt.Dimension(500, 500));
        scanp.setMinimumSize(new java.awt.Dimension(500, 25));
        scanp.setLayout(new java.awt.BorderLayout());

        scan.setText("Kedaruge");
        scan.setMaximumSize(new java.awt.Dimension(300, 25));
        scan.setMinimumSize(new java.awt.Dimension(300, 25));
        scan.setPreferredSize(new java.awt.Dimension(300, 25));
        scanp.add(scan, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(scanp);

        tradutorp.setBorder(javax.swing.BorderFactory.createTitledBorder("TRADUTOR:"));
        tradutorp.setMaximumSize(new java.awt.Dimension(500, 500));
        tradutorp.setMinimumSize(new java.awt.Dimension(500, 25));
        tradutorp.setLayout(new java.awt.BorderLayout());

        tradutor.setMaximumSize(new java.awt.Dimension(300, 25));
        tradutor.setMinimumSize(new java.awt.Dimension(300, 25));
        tradutor.setPreferredSize(new java.awt.Dimension(300, 25));
        tradutorp.add(tradutor, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(tradutorp);

        capitulop.setBorder(javax.swing.BorderFactory.createTitledBorder("CAPITULO:"));
        capitulop.setMaximumSize(new java.awt.Dimension(500, 500));
        capitulop.setMinimumSize(new java.awt.Dimension(500, 25));
        capitulop.setLayout(new java.awt.BorderLayout());

        capitulo.setText("1");
        capitulo.setMaximumSize(new java.awt.Dimension(300, 25));
        capitulo.setMinimumSize(new java.awt.Dimension(300, 25));
        capitulo.setPreferredSize(new java.awt.Dimension(300, 25));
        capitulop.add(capitulo, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(capitulop);

        paginasp.setBorder(javax.swing.BorderFactory.createTitledBorder("PAGINAS:"));
        paginasp.setMaximumSize(new java.awt.Dimension(500, 500));
        paginasp.setMinimumSize(new java.awt.Dimension(500, 25));
        paginasp.setLayout(new java.awt.BorderLayout());

        paginas.setText("1");
        paginas.setMaximumSize(new java.awt.Dimension(300, 25));
        paginas.setMinimumSize(new java.awt.Dimension(300, 25));
        paginas.setPreferredSize(new java.awt.Dimension(300, 25));
        paginasp.add(paginas, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(paginasp);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        botoes.setMaximumSize(new java.awt.Dimension(500, 500));
        botoes.setMinimumSize(new java.awt.Dimension(500, 25));

        jButton1.setText("OK");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        botoes.add(jButton1);

        jButton2.setText("Voltar");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        botoes.add(jButton2);

        getContentPane().add(botoes, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(494, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (DataHolder.getInstance().dadosGerais == null) {
            DataHolder.getInstance().dadosGerais = new DadosGerais(
                    this.obra.getText(),
                    this.scan.getText(),
                    this.tradutor.getText(),
                    this.capitulo.getText(),
                    1
            );
        }
        WindowStack.getInstance().stack.add(this);
        new JanelaPagina().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (!WindowStack.getInstance().stack.isEmpty()) {
                JFrame pop = WindowStack.getInstance().stack.pop();
                
                pop.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDadosGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDadosGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDadosGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDadosGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaDadosGerais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoes;
    private javax.swing.JTextField capitulo;
    private javax.swing.JPanel capitulop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField obra;
    private javax.swing.JPanel obrap;
    private javax.swing.JTextField paginas;
    private javax.swing.JPanel paginasp;
    private javax.swing.JTextField scan;
    private javax.swing.JPanel scanp;
    private javax.swing.JTextField tradutor;
    private javax.swing.JPanel tradutorp;
    // End of variables declaration//GEN-END:variables
}
