/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import helper.DataHolder;
import helper.WindowStack;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.border.TitledBorder;
import objetos.DadosGerais;
import objetos.Dialogo;
import objetos.Pagina;

/**
 *
 * @author macha
 */
public class JanelaPagina extends javax.swing.JFrame {

    public DadosGerais dadosGerais = DataHolder.getInstance().dadosGerais;

    /**
     * Creates new form JanelaPagina
     */
    public JanelaPagina() {
        initComponents();
        setTitle(dadosGerais.getWorkingArea());
        ((TitledBorder) this.paginaTitulo.getBorder()).setTitle("Pagina " + (dadosGerais.paginaIndex + 1) + " de  " + (dadosGerais.ultimaPagina + 1));
        ((TitledBorder) this.quadroTitulo.getBorder()).setTitle("Quadro " + (dadosGerais.pagina().quadrosIndex + 1) + " de " + (dadosGerais.pagina().ultimoQuadro + 1));
        ((TitledBorder) this.dialogoTitulo.getBorder()).setTitle("Dialogo " + (dadosGerais.pagina().quadro().dialogosIndex + 1) + " de " + (dadosGerais.pagina().quadro().ultimoDialogo + 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        solto = new javax.swing.JCheckBox();
        fonteDiferente = new javax.swing.JCheckBox();
        dialogoTitulo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ad = new javax.swing.JButton();
        pd = new javax.swing.JButton();
        quadroTitulo = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        aq = new javax.swing.JButton();
        pq = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        vq = new javax.swing.JButton();
        paginaTitulo = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        ap = new javax.swing.JButton();
        pp = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        vp = new javax.swing.JButton();
        botoes = new javax.swing.JPanel();
        botoes2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));

        center.setLayout(new javax.swing.BoxLayout(center, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dialogo"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto"));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        texto.setLineWrap(true);
        texto.setRows(5);
        jScrollPane2.setViewportView(texto);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        solto.setMnemonic('Q');
        solto.setText("Texto Solto");
        jPanel7.add(solto);

        fonteDiferente.setMnemonic('W');
        fonteDiferente.setText("Fonte Diferente");
        jPanel7.add(fonteDiferente);

        jPanel6.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        dialogoTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dialogo 1 de 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        dialogoTitulo.setLayout(new javax.swing.BoxLayout(dialogoTitulo, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        ad.setText("<");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        jPanel5.add(ad);

        pd.setMnemonic('A');
        pd.setText(">");
        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        jPanel5.add(pd);

        dialogoTitulo.add(jPanel5);

        jPanel1.add(dialogoTitulo, java.awt.BorderLayout.SOUTH);

        center.add(jPanel1);

        quadroTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quadro 1 de 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        quadroTitulo.setLayout(new javax.swing.BoxLayout(quadroTitulo, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel10.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        aq.setText("<");
        aq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aqActionPerformed(evt);
            }
        });
        jPanel10.add(aq);

        pq.setMnemonic('S');
        pq.setText(">");
        pq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pqActionPerformed(evt);
            }
        });
        jPanel10.add(pq);

        quadroTitulo.add(jPanel10);

        jPanel14.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel14.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        vq.setText("Ver Quadro");
        vq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vqActionPerformed(evt);
            }
        });
        jPanel14.add(vq);

        quadroTitulo.add(jPanel14);

        center.add(quadroTitulo);

        paginaTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagina 1 de 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        paginaTitulo.setLayout(new javax.swing.BoxLayout(paginaTitulo, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel12.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        ap.setText("<");
        ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apActionPerformed(evt);
            }
        });
        jPanel12.add(ap);

        pp.setMnemonic('D');
        pp.setText(">");
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        jPanel12.add(pp);

        paginaTitulo.add(jPanel12);

        jPanel15.setPreferredSize(new java.awt.Dimension(500, 25));
        jPanel15.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        vp.setText("Ver Pagina");
        vp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpActionPerformed(evt);
            }
        });
        jPanel15.add(vp);

        paginaTitulo.add(jPanel15);

        center.add(paginaTitulo);

        getContentPane().add(center, java.awt.BorderLayout.CENTER);

        botoes.setMaximumSize(new java.awt.Dimension(500, 500));
        botoes.setMinimumSize(new java.awt.Dimension(500, 25));
        botoes.setLayout(new java.awt.BorderLayout());

        botoes2.setMaximumSize(new java.awt.Dimension(500, 500));
        botoes2.setMinimumSize(new java.awt.Dimension(500, 25));

        jButton6.setText("OK");
        jButton6.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        botoes2.add(jButton6);

        Salvar.setText("Salvar");
        Salvar.setPreferredSize(new java.awt.Dimension(100, 25));
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        botoes2.add(Salvar);

        jButton7.setText("Voltar");
        jButton7.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        botoes2.add(jButton7);

        botoes.add(botoes2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(botoes, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(345, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        preencheDialogo(dadosGerais.pagina().quadro().dialogo());
        pegaDadosDialogo(dadosGerais.pagina().quadro().proximaDialogo());
        repaint();
    }//GEN-LAST:event_pdActionPerformed

    private void preencheDialogo(Dialogo dialogo) {
        dialogo.conteudo = this.texto.getText();
        dialogo.textoSolto = this.solto.isSelected();
        dialogo.textoFonteDiferente = this.fonteDiferente.isSelected();
    }

    private void vqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vqActionPerformed
        new ExibirTexto(this, false, dadosGerais.pagina().quadro().exibirQuadro()).setVisible(true);
    }//GEN-LAST:event_vqActionPerformed

    private void vpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpActionPerformed
        new ExibirTexto(this, false, dadosGerais.pagina().exibirPagina()).setVisible(true);
    }//GEN-LAST:event_vpActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        preencheDialogo(dadosGerais.pagina().quadro().dialogo());
        pegaDadosDialogo(dadosGerais.pagina().quadro().anteriorDialogo());
        repaint();
    }//GEN-LAST:event_adActionPerformed

    private void pegaDadosDialogo(Dialogo anteriorDialogo) {
        this.texto.setText(anteriorDialogo.conteudo);
        this.solto.setSelected(anteriorDialogo.textoSolto);
        this.fonteDiferente.setSelected(anteriorDialogo.textoFonteDiferente);
        ((TitledBorder) this.dialogoTitulo.getBorder()).setTitle("Dialogo " + (dadosGerais.pagina().quadro().dialogosIndex + 1) + " de " + (dadosGerais.pagina().quadro().ultimoDialogo + 1));
        this.texto.requestFocus();
    }

    private void pqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqActionPerformed
        preencheDialogo(dadosGerais.pagina().quadro().dialogo());
        pegaDadosDialogo(dadosGerais.pagina().proximaQuadro().dialogo());

        ((TitledBorder) this.quadroTitulo.getBorder()).setTitle("Quadro " + (dadosGerais.pagina().quadrosIndex + 1) + " de " + (dadosGerais.pagina().ultimoQuadro + 1));
        repaint();
    }//GEN-LAST:event_pqActionPerformed

    private void aqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aqActionPerformed
        preencheDialogo(dadosGerais.pagina().quadro().dialogo());
        pegaDadosDialogo(dadosGerais.pagina().anteriorQuadro().dialogo());

        ((TitledBorder) this.quadroTitulo.getBorder()).setTitle("Quadro " + (dadosGerais.pagina().quadrosIndex + 1) + " de " + (dadosGerais.pagina().ultimoQuadro + 1));
        repaint();
    }//GEN-LAST:event_aqActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        preencheDialogo(dadosGerais.pagina().quadro().dialogo());
        pegaDadosDialogo(dadosGerais.proximaPagina().quadro().dialogo());

        ((TitledBorder) this.paginaTitulo.getBorder()).setTitle("Pagina " + (dadosGerais.paginaIndex + 1) + " de  " + (dadosGerais.ultimaPagina + 1));
        ((TitledBorder) this.quadroTitulo.getBorder()).setTitle("Quadro " + (dadosGerais.pagina().quadrosIndex + 1) + " de " + (dadosGerais.pagina().ultimoQuadro + 1));
        repaint();
    }//GEN-LAST:event_ppActionPerformed

    private void apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apActionPerformed
        preencheDialogo(dadosGerais.pagina().quadro().dialogo());
        pegaDadosDialogo(dadosGerais.anteriorPagina().quadro().dialogo());

        ((TitledBorder) this.paginaTitulo.getBorder()).setTitle("Pagina " + (dadosGerais.paginaIndex + 1) + " de  " + (dadosGerais.ultimaPagina + 1));
        ((TitledBorder) this.quadroTitulo.getBorder()).setTitle("Quadro " + (dadosGerais.pagina().quadrosIndex + 1) + " de " + (dadosGerais.pagina().ultimoQuadro + 1));
        repaint();
    }//GEN-LAST:event_apActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new ExibirTexto(this, false, dadosGerais.exibirCapitulo()).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (!WindowStack.getInstance().stack.isEmpty()) {
                JFrame pop = WindowStack.getInstance().stack.pop();
                pop.setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        GsonBuilder builder = new GsonBuilder();
        builder.setPrettyPrinting();
        Gson create = builder.create();
        String toJson = create.toJson(dadosGerais);

        try (FileWriter fileWriter = new FileWriter("C:\\Users\\macha\\Documents\\tempTraducaoFile.")) {
            fileWriter.write(toJson);
            fileWriter.flush();
        } catch (IOException ex) {
            Logger.getLogger(JanelaPagina.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SalvarActionPerformed

    public void setDialogo(Dialogo d) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPagina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salvar;
    private javax.swing.JButton ad;
    private javax.swing.JButton ap;
    private javax.swing.JButton aq;
    private javax.swing.JPanel botoes;
    private javax.swing.JPanel botoes2;
    private javax.swing.JPanel center;
    private javax.swing.JPanel dialogoTitulo;
    private javax.swing.JCheckBox fonteDiferente;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel paginaTitulo;
    private javax.swing.JButton pd;
    private javax.swing.JButton pp;
    private javax.swing.JButton pq;
    private javax.swing.JPanel quadroTitulo;
    private javax.swing.JCheckBox solto;
    private javax.swing.JTextArea texto;
    private javax.swing.JButton vp;
    private javax.swing.JButton vq;
    // End of variables declaration//GEN-END:variables
}
